#!/usr/bin/env bash
# a script that configures a new Ubuntu machine to install nginx web server

# update the package index and install Nginx
apt-get update
apt-get install -y nginx

# config nginx to listen on port 80
sed -i 's/#listen 80/listen 80/' /etc/nginx/sites-available/default

# start/restart nginx
service nginx start

# if nginx fails to run
if [[ ! $? ]]; then
    echo "Error: Nginx failed to start."
    exit 1
fi

# create a temp index.html file
echo "Hello World!" > /var/www/html/index.html
