#!/usr/bin/env bash
#	a script that displays listening ports:
#+	only shows listening sockets
#+	shows the PID and name of program to which eash socket belongs
netstat --tcp --udp --listening --program --unix
