#!/usr/bin/env bash
# configures a sever or ubuntu container to listen on port 80 of all active IPv4 IPs

# remove default config file then create symlink to sites-enabled
rm /etc/nginx/sites-enabled/default

# symlink creation
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx service
service nginx restart
