#!/usr/bin/env bash
# configures a sever or ubuntu container to listen on port 80 of all active IPv4 IPs
sed -i 's/8080 default_server/80 default_server/' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
