#!/usr/bin/env bash
#   bash script that;
#+      creates the file /var/run/myscript.pid containing its PID
#+      displays To infinity and beyond indefinitely
#+      displays I hate the kill command when receiving a SIGTERM signal
#+      displays Y U no love me?! when receiving a SIGINT signal
#+      deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"
function perform_cleanup_on_sigterm
{
    echo "I hate the kill command"
    rm -f "$file"
    exit
}

function sigint_handler
{
    echo "Y U no love me?!"
    rm -f "$file"
    exit
}

function sigquit_handler
{
    rm -f "$file"
    exit
}

trap perform_cleanup_on_sigterm SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

echo $$ > "$file"

while true;
do
    echo "To infinity and beyond"
    sleep 2
done
