#!/usr/bin/env bash
#   displays numbers from 1-100
#   FizzBuzz --- multiple of 3 and 5
#+  Fizz     --- multiple of 3
#+  Buzz     --- multiple of 5

i=1
while [ "$i" -le 100 ];
do
    if [ $((i%15)) -eq 0 ];
    then
        echo "FizzBuzz"
    elif [ $((i%3)) -eq 0 ];
    then
        echo "Fizz"
    elif [ $((i%5)) -eq 0 ];
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done
