#!/usr/bin/env bash
#   displays the time for 12 hours and 59 minutes
#   hours from 0-12
#   minutes from 1-59

hr=0
while [ "$hr" -le 12 ];
do
    echo "Hour: $hr"
    min=1
    while [ "$min" -le 59 ];
    do
        echo "$min"
        ((min++))
    done
    ((min = 1))
    ((hr++))
done
