#!/usr/bin/env bash
#   gives information about `school` file

file_name="school"
#   if file exists check
if [ -e "$file_name" ];
then
    echo "school file exists"
    #   if file exists is not empty check
    if [ -s "$file_name" ];
    then
        echo "school file is not empty"
    #   if empty...
    else
        echo "school file is empty"
    fi

    # if file is a regular file check
    if [ -f "$file_name" ];
    then
        echo "school is a regular file"
    fi
#   if file does not exist
else
    echo "school file does not exist"
fi
