#!/usr/bin/env bash
#	a script that configures an Ubuntu server with
#+	`localhost` resolving to `127.0.0.2`
#+	`facebook.com` resolving to `8.8.8.8`
cp /etc/hosts ~/hosts.n
echo "127.0.0.2	localhost" > ~/hosts.n
echo "8.8.8.8		facebook.com" >> ~/hosts.n
cat ~/hosts.n > /etc/hosts
